### ISSUE TITLE
Odoo Backend Created quotations causing Errors with Portal Access  (magento_bind_ids not found)

### ISSUE THREAD

**Issue by l-arnold** [OCA/connector-magento#102]
Just did a fresh install of the connector.  Some errors showing up in normal activity.  I realize that there may be some "odoo" only issues here on the Portal, but 2 of the 3 are referencing Magento Bindings which I do not believe were involved in these quotes or invoices.

Depending upon how I get to this, I am getting a consitent error whereby an Magento Related customer cannont seemingly access their backend created quotation via the Odoo Portal.  This functionality should remain it seems to me.  Very important absence from Magento and it is important that this can be in Odoo capabilites (was in Openerp7 with Connector)

---

After Logging in on the back end, when I see related quotes for the portal customer, choosing a Quote I get a series of errors visible:

On the specific quotation referenced in email:  
                     AccessError

```
                 No value found for sale.order(15,).magento_bind_ids
```

On a prior quotation listed on the portal:

AccessError

```
                  The requested operation cannot be completed due to security restrictions. Please contact your system administrator.

                  (Document type: res.partner, Operation: read)
```

On a invoice listed on the customer portal:

AccessError

```
                  Sorry, you are not allowed to access this document. Only users with the following access level are currently allowed to do that:
                  - Accounting & Finance/Invoicing & Payments
                  - Connector/Connector Manager

                  (Document model: magento.account.invoice)
```

---

end of post

**Comment by l-arnold** [comment]
Saw one recomended fix for general errors of the sort of "upgrading base".  I did so and it changed my home landing to Connectors (perhaps just a one time).  Did not fix the access issue however with the portal user. 

```
   No value found for sale.order(15,).magento_bind_ids
```

Will Revert to snapshot before upgrading base.

**Comment by guewen** [comment]
These errors seems to be access rights errors.
Portal users don't have access to the bindings (`magento.*` models) and you may want to add these accesses or hide the fields.

**Comment by l-arnold** [comment]
I spent a very large amount of time looking at this.  I could not find a way to "hide the fields" on Portal Access to Sales Order or an Invoice.  I came around, having made about 6 spreadsheets to the following.  The 1st and 3rd Errors went away (Error 2 portal seemed customer mapping related)

I feel this is "brute force" but what I did was add READ ONLY Access Rights of a "Portal Group" 
to each of the following models (used a description similar to connectors but "portal" referenced:

```
 Model descrip / Magento Invoice ie: magento_invoic_portal  (w/ missing e)
 Model descrip / Magento Address ie magento_address_portal_user
 Model descrip / Magento Binding (abstract)  Ie: magento_binding_portal_user
```

model descrip:  Magento Sale Order ie magento_sale_order_portal
model descrip:  Magento Sale Order Line  ie: magento_sale_order_line_portal

Finally, I got a bit confused as the Name was shared but not the model:

```
 model name:  magento.res.partner.category (Model Name is same as above "Magento Binding  (abstract) " SAME NAME ??   In addition to Connector Manager group, this model also has the group Employee    magento_res_partner_category group_user)
```

I expect this is Over the Top Fixes but not sure honestly.  I can peel them back now one at a time and see if Portal still works.

Are there other consequences to this approach?  It may need to be worked into the connector or some alternative found.  I feel the Portal access is important.  I also think it would be helpful to show Magento Orders/Invoices in the Portal (would seem default and likely is)

**Comment by l-arnold** [comment]
I thought I would look at how to plug in on Github.  

```
 magentoerpconnect/security/ir.model.access.csv
```

Seems like the place but because every row has four columns and I wouldn't want to be throwing things around, probably not the path.  Have others tested that the portal module in Odoo is working properly for them?  My situation involved a customer who existed in Odoo and Also in Magento.  Seem to have been bound in the Connector import Customers process.

Created a Quotation in Odoo, emailed in Odoo.  Customer logged into Portal and ran into erros noted at top.

Seems there is a simpler way to grant Portal Users access to files which have elements (empty or not) of MagentoConnector.  Perhaps my not working is a fluke but all real fresh, no changes.

**Comment by guewen** [comment]
I think there is nothing we can do here as `magentoerpconnect` does not depend on `portal`. So either you configure the access rights on your instance, either you create a `magentoerpconnect_portal` module that depends on both `magentoerpconnect` and `portal` and create the appropriate access rights (in the latter case yes you would want to create a `ir.model.access.csv` file with the grants).
