### ISSUE TITLE
Importing orders but nothing listed

### ISSUE THREAD

**Issue by thomich** [OCA/connector-magento#105]
I tried out magento buildout from @guewen and i can't get orders into odoo from magento

Importing Partner Categories, Product Categories and Products works fine, but not for orders.

I see that some order imports are in queue and will be processed, but no sale orders available.

What is the cause? What do i miss?

I checked out http://odoo-magento-connector.com/guides/installation_guide.html#installation but can't find why it does not import orders...

Thanks for answer

**Comment by guewen** [comment]
You way you have jobs for sales orders which stay in pending or enqueued, is that true ?

How are configured their payment methods? They could be configured to be imported only when they are paid so the jobs would be waiting for the payment. Or the jobs could be set directly to done without importing the order if the payment method is configured to cancel the import if an order is not paid within 30 days.

**Comment by thomich** [comment]
okey.. thanks @guewen, got it.. it was about unpaid orders and the payment option about days
