### ISSUE TITLE
Configurable Products Sync

### ISSUE THREAD

**Issue by aignermi** [OCA/connector-magento#107]
hi guys,

all our products in Magento are configurable products with associated simple products. When I sync them to Odoo, I just get all the simple products. Why are they not grouped correctly with Variants? In your documentation you specified that you support simple and configurable products: "But, as of today, only simple and configurable products are supported."

thanks,
michael

**Comment by guewen** [comment]
@aignermi the configurable products are well handled in sales orders, so the feature exists.
The products are imported as simple products and not as variant products because the Magento API does not contain this information when we import the products.
