### ISSUE TITLE
Don´t sync category

### ISSUE THREAD

**Issue by fohnbit** [OCA/connector-magento#108]
Hello!

Can I modify the files, that the connector don´t sync the category?
In Odoo all my prices are based on different price lists and they are connected to the category.

On each import he overwrite my own category.

I want only that he write not the category to the product. The categories tree of course I need in odoo.

Thank you!

**Comment by guewen** [comment]
You should not modify directly the files in the addon. Instead, you should write an extension addon that modifies this behavior. You should probably extend the ProductMapper and remove the category_id mapping. Use the documentation for how to write this extension addon: http://odoo-magento-connector.com/guides/tutorial_customize.html

**Comment by fohnbit** [comment]
Hello!

Ok, thank you .. .but maybe you can give me a hint, in which file I found the command, where the connector write the product and category.
Then I could check for a change.

**Comment by guewen** [comment]
Here it is: https://github.com/OCA/connector-magento/blob/8.0/magentoerpconnect/product.py#L464-L491

**Comment by fohnbit** [comment]
Dear guewen,

many thanks for your support!
But I guess this is the main category import?
This is ok and I need to use.

I only want to disable, that the connector write in odoo the "Internal Category" to the imported products.

Thank you and have a great sunday!

**Comment by guewen** [comment]
Hi,

It is the "Internal Category", the field named `categ_id`. (Which is not different from the "Main category" or I miss something.)

**Comment by fohnbit** [comment]
Hello!

Again thank you for your help ... guess I describe it maybe not good enough:
I want disable, that the connector write the Main category on the products in odoo.

According to your link I try this:
 @mapping
    def website_ids(self, record):
        website_ids = []
        binder = self.binder_for('magento.website')
        for mag_website_id in record['websites']:
            website_id = binder.to_openerp(mag_website_id)
            website_ids.append((4, website_id))
        return {'website_ids': website_ids}

```
@mapping
def categories(self, record):
    mag_categories = record['categories']
    binder = self.binder_for('magento.product.category')

    category_ids = []
    main_categ_id = None

    for mag_category_id in mag_categories:
        cat_id = binder.to_openerp(mag_category_id, unwrap=True)
        if cat_id is None:
            raise MappingError("The product category with "
                               "magento id %s is not imported." %
                               mag_category_id)

        category_ids.append(cat_id)

   # if category_ids:
     #   main_categ_id = category_ids.pop(0)

   # if main_categ_id is None:
     #   default_categ = self.backend_record.default_category_id
     #   if default_categ:
      #      main_categ_id = default_categ.id

   # result = {'categ_ids': [(6, 0, category_ids)]}
   # if main_categ_id:  # OpenERP assign 'All Products' if not specified
   #     result['categ_id'] = main_categ_id
    return result
```

Maybe I disable the wrong lines, but he write still the Main category on the products.
Did I use the false line or must I disable also the "return result" ?

Thank you!!
