### ISSUE TITLE
Imported Salesorders have wrong tax-settings

### ISSUE THREAD

**Issue by aignermi** [OCA/connector-magento#109]
Hi,

I'm not sure if this is a configuration issue or a real issue. I configured the "Prices include tax" setting to Yes, as our prices in Magento are already with tax. When I import the sales orders now from Magento, Odoo is calculating 19%VAT on top of the price of the product which already includes VAT (eg. product price is 69€ incl. tax, sales order with this product total is 82.11€). So this is not correct. Can you please help me figure that out?

Thanks,
Michael

**Comment by guewen** [comment]
The Magento API does not give much information about the taxes being used, so we use the taxes configured on the product on Odoo. According to your description, it seems that the tax configured on your odoo product is tax inclusive wether it should be tax exclusive.

**Comment by aignermi** [comment]
Thanks Guewen for your quick answer, I just also found out that the connector adds a message to the imported sales-orders:

"Total Tax Amount differs from Magento
Description
The tax amount computed in OpenERP doesn't match with the tax amount in Magento.

Cause:
The taxes are probably different between OpenERP and Magento. A fiscal position could have changed the final price.

Resolution:
Check your taxes and fiscal positions configuration and correct them if necessary."

Nonetheless I will try it out as you suggested.

**Comment by guewen** [comment]
I close this issue, still you can reopen it if you think there is a real bug.

**Comment by aignermi** [comment]
For everyone who is running into the same issue, the answer from Guwen solved it:

"According to your description, it seems that the tax configured on your odoo product is tax inclusive wether it should be tax exclusive."
