### ISSUE TITLE
While import sale order, correct product is not set inside shipping line according to carrier method.

### ISSUE THREAD

**Issue by ghost** [OCA/connector-magento#112]
While import sale order from Magento to Odoo, always default product "[SHIP]" is set inside shipping line of that order. Even though we have specified product inside carrier method of that order.

System is not going to getting correct product from selected carrier method of that order instead of system always taking default service product which have external id "connector_ecommerce.product_product_shipping". 

We have been tested with Odoo V8. Also getting it inside OpenERP V7.

**Comment by guewen** [comment]
Could you test this patch #114 and report back you result on the pull request?

**Comment by ghost** [comment]
I have report back with your given changes. Please have a look on it. Thanks :)

**Comment by guewen** [comment]
Sorry, I didn't saw your pull request that's why I proposed another one :see_no_evil:

**Comment by guewen** [comment]
@emiprotechnologies could you have the information you want? Are you going to move forwards with the CLA?

**Comment by ghost** [comment]
I have signed CLA. Where can I see list of CLA members ? Where can I see my own details ?
Thanks.

**Comment by elicoidal** [comment]
I have a ICLA on Chirag Rajkotiya for this github in our DB. I should be good for the bot
If you have more msg for clabot, contact me
