### ISSUE TITLE
Dependency up to date ?

### ISSUE THREAD

**Issue by nbessi** [OCA/connector-magento#126]
In the documentation it is written : 

```

Important

Please check if you have installed Magento on PHP with a 5.4.x* version.
Magento is not compatible with this version and would prevent the API to behave normally. 
In that case, you must retrograde to PHP 5.3.x or apply the patch provided by Magento (see http://magento.com/resources/system-requirements)
```

http://magento.com/resources/system-requirements tells something different. Is the doc obsolete or is there an other subtlety?

**Comment by guewen** [comment]
This notice applies to Magento 1.7, it has been fixed in Magento 1.9. I think we could replace `Magento` with `Magento 1.7` to be more specific about the version.
