### ISSUE TITLE
Everything is fine but nothing is imported

### ISSUE THREAD

**Issue by autoslide** [OCA/connector-magento#135]
Hello,
After updated Magento 1.9.2.1 the import controls work fine but when I look at the purchase order or clients I have nothing imported.
I do not have to display bug.
Nothing in the logs.
My oddo logs

```
2015-08-27 14:16:22,359 4191 INFO Autoslide openerp.addons.magentoerpconnect.sale: search for magento saleorders {'created_at': {'to': '2015/08/27 14:15:23', 'from': '2015/08/27 13:47:55'}, 'store_id': {'in': [u'0']}, 'state': {'neq': 'canceled'}} returned []
2015-08-27 14:16:23,834 4191 INFO Autoslide openerp.addons.magentoerpconnect.product: search for magento products {'updated_at': {'to': '2015/08/27 14:15:22', 'from': '2015/08/27 13:47:54'}} returned []
```

My apache log

```
autoslide.fr:80 92.222.7.206 - - [27/Aug/2015:16:16:23 +0200] "POST /index.php/api/xmlrpc HTTP/1.1" 200 847 "-" "xmlrpclib.py/1.0.1 (by www.pythonware.com)"
autoslide.fr:80 92.222.7.206 - - [27/Aug/2015:16:16:23 +0200] "POST /index.php/api/xmlrpc HTTP/1.1" 200 887 "-" "xmlrpclib.py/1.0.1 (by www.pythonware.com)"
autoslide.fr:80 92.222.7.206 - - [27/Aug/2015:16:16:23 +0200] "POST /index.php/api/xmlrpc HTTP/1.1" 200 818 "-" "xmlrpclib.py/1.0.1 (by www.pythonware.com)"
autoslide.fr:80 92.222.7.206 - - [27/Aug/2015:16:16:23 +0200] "POST /index.php/api/xmlrpc HTTP/1.1" 200 848 "-" "xmlrpclib.py/1.0.1 (by www.pythonware.com)"
autoslide.fr:80 92.222.7.206 - - [27/Aug/2015:16:16:23 +0200] "POST /index.php/api/xmlrpc HTTP/1.1" 200 891 "-" "xmlrpclib.py/1.0.1 (by www.pythonware.com)"
autoslide.fr:80 92.222.7.206 - - [27/Aug/2015:16:16:23 +0200] "POST /index.php/api/xmlrpc HTTP/1.1" 200 818 "-" "xmlrpclib.py/1.0.1 (by www.pythonware.com)"
autoslide.fr:80 92.222.7.206 - - [27/Aug/2015:16:16:23 +0200] "POST /index.php/api/xmlrpc HTTP/1.1" 200 847 "-" "xmlrpclib.py/1.0.1 (by www.pythonware.com)"
autoslide.fr:80 92.222.7.206 - - [27/Aug/2015:16:16:23 +0200] "POST /index.php/api/xmlrpc HTTP/1.1" 200 821 "-" "xmlrpclib.py/1.0.1 (by www.pythonware.com)"
autoslide.fr:80 92.222.7.206 - - [27/Aug/2015:16:16:23 +0200] "POST /index.php/api/xmlrpc HTTP/1.1" 200 818 "-" "xmlrpclib.py/1.0.1 (by www.pythonware.com)"
```

Any help please.

Regards

**Comment by guewen** [comment]
Hi,

You can see here the criteria filters: `{'updated_at': {'to': '2015/08/27 14:15:22', 'from': '2015/08/27 13:47:54'}}` and here the result returned by Magento: `[]`. Magento returns nothing.
Are you sure that products have been updated in this timerange?

**Comment by autoslide** [comment]
Hi,
I do not have new products but I created a new order on Magento with a new customer but I do not see anything imported in sales or customers, or purchase order.
Possible permissions files or directory?

**Comment by guewen** [comment]
You should not see purchase orders anyway, but sales orders yes.
If you look in the Connector Jobs and remove the filters, what jobs do you have? Do you have "import records" jobs or only "import batch" jobs?

**Comment by autoslide** [comment]
In a first time i see "Prepare a batch import of records from Magento" and after "Import a record from Magento" with "finished" mention.

**Comment by guewen** [comment]
Ok, and what is the function of "Import a record from Magento"?

**Comment by autoslide** [comment]
I do not know if I understand your question but I try to import a Magento sale order record with this customer.

**Comment by guewen** [comment]
could you send a screenshot of the form view of this job?

**Comment by autoslide** [comment]
I can see 2 jobs:
 	 Prepare a batch import of records from Magento 	magento.sale.order	Terminé		27/08/2015 16:56:39	27/08/2015 16:56:41	47b68a7d-d070-4c69-9ec4-7dfea90beffa	root.magento

**Comment by autoslide** [comment]
![sans titre 1](https://cloud.githubusercontent.com/assets/13170028/9524048/1436261a-4cdd-11e5-831b-8fcf9845a8b0.jpg)

**Comment by guewen** [comment]
I meant the other one "Import a record"

**Comment by autoslide** [comment]
I do not have "Import a record" for sale order or customers just this for "magento.res.partner" :
![sans titre2](https://cloud.githubusercontent.com/assets/13170028/9524205/e8d404f0-4cdd-11e5-8570-72dae2295bb7.jpg)

I want to tell you that I did not have this problem before.

**Comment by guewen** [comment]
Ok, so you should have a partner tag which has been imported.
From what I see, it is just that you have no data returned by Magento. Can you check if have ntp on the Magento server? Because it could be that they don't communicate with their clocks synchronized.

**Comment by autoslide** [comment]
![sans titre 3](https://cloud.githubusercontent.com/assets/13170028/9524506/9bb5cee0-4cdf-11e5-933f-924c5b1cfffa.jpg)
Before updating Magento August 19:

**Comment by autoslide** [comment]
Magento and odoo are on the same server

**Comment by guewen** [comment]
I fear I can't help you more. You should try do to direct calls directly with https://pypi.python.org/pypi/magento and see if that matches with what you have in Magento. 

But the 2 lines here:

```
2015-08-27 14:16:22,359 4191 INFO Autoslide openerp.addons.magentoerpconnect.sale: search for magento saleorders {'created_at': {'to': '2015/08/27 14:15:23', 'from': '2015/08/27 13:47:55'}, 'store_id': {'in': [u'0']}, 'state': {'neq': 'canceled'}} returned []
2015-08-27 14:16:23,834 4191 INFO Autoslide openerp.addons.magentoerpconnect.product: search for magento products {'updated_at': {'to': '2015/08/27 14:15:22', 'from': '2015/08/27 13:47:54'}} returned []
```

 indicates clearly that Magento returns nothing for between the dates in the filter.

**Comment by autoslide** [comment]
Don't you think this could be a problem of files permissions because there's two days i changed  the permissions of files and directories as recommended Magento after the update?
I also remove the module 'comunity' I reinstalled afterwards because I have had problems updates.
May be i need to reinstall openerp connector module in magento?
Do you have a point of view on these issues.
Thank you for your time and patience.

**Comment by guewen** [comment]
If it was a permission issue or an installation issue of the magento module, I think it would not return an empty list but an error. 

Did you try to modify the "Import from date" field on the storeviews on odoo on a past date?

Just thought about something: it seems it only tries to import sales orders from the 'admin' storeviews. Can you check on odoo on the storeview of the Import of sales orders is enabled?

**Comment by autoslide** [comment]
Many thanks Guewen but i restore a snapshot because i dont have success. Now all is fine.
I not try to check on the storeview because i see your post too late.
Best regards and see you...

**Comment by autoslide** [comment]
I understood my problem because it happened again. In fact when i delete a saleorder in odoo or a customer which was synchronized, its not possible to be re-synchronized again because Odoo keeps track of the transaction somewhere.
Do you know a way to clear effectively a sale order in odoo after mishandling? That would be helpful.

**Comment by guewen** [comment]
It does not keep a trace if you delete them.
However, it keep the "last date of import" in the Magento backend, store and storeviews.
So if you create a sales order on Magento at time `T`, you import it in odoo at time `T+1`, odoo keeps `T+1` in the "last date of import". Now if you delete the sales order at `T+2` and rerun the sync expecting it to get you initial order, it won't get it because it imports orders from `T+1`.
If you want it to to import again sales orders from `T`, you just have to modify the dates on Odoo on the magento storeviews.
