### ISSUE TITLE
Unable to import product quantities from Magento to Odoo

### ISSUE THREAD

**Issue by salishaukat** [OCA/connector-magento#138]
Hi
Unable to import product quantities from magento to odoo , the inventory odoo shows 0 for every product that is imported from magento to odoo

**Comment by guewen** [comment]
Hi, 

There is no such feature. The stock quantities synchronisation is the other way around: Odoo drives the stock quantities and send updates to Magento.
Usually people run an initial inventory at the go-live of their project.
