### ISSUE TITLE
Upgrade process:  Does"-u" update the Data Structures also.

### ISSUE THREAD

**Issue by l-arnold** [OCA/connector-magento#141]
Guewen,

At the close of issue #132 
You wrote

... before any upgrade, always do a backup of your database. Then, do a git pull on every branch, stop your server and start it again with the option -u base in order to update the modules."
Does this also update the database in the case there has been any data structure changes in the new git pulls?

Thanks in advance.

**Comment by guewen** [comment]
This is the purpose of the `-u` option yes.

**Comment by l-arnold** [comment]
Thank you Guewen.

What  the  full text of your update call?  Do you ever script that call? 

 It would seem that the update process would be built into the Odoo restore database (database management) process. Do you know if it is by default?

Thanks for your help .

**Comment by l-arnold** [comment]
All good it seems. Does seem scripting the git pull and upgrade lines would make sense.  Perhaps even a syatem check at startup.
