### ISSUE TITLE
How can I map my attribute from magento to odoo?

### ISSUE THREAD

**Issue by snowleo208** [OCA/connector-magento#147]
Hello, I had import my orders and product to odoo, but I have my own attribute called "barcode" which is a JAN code, I would like to map it to ean13 or other customized fields, how can I do that? Also I had a attribute called release which is for release dates, can I also map to odoo?

Is it possible to do this without lots of programming languages? Since I am not a programmer... Thanks!

**Comment by guewen** [comment]
Hi,

No you can't do it without programming. If anyway you want to go that way, you can start with this guide: http://odoo-magento-connector.com/guides/tutorial_customize.html

I close as it is not a real issue on the project. Consider subscribing on the project's mailing list: https://launchpad.net/~openerp-connector-community
