### ISSUE TITLE
Jobrunner setup kills wkhtmltox (with wkhtmltopdf error -11)

### ISSUE THREAD

**Issue by l-arnold** [OCA/connector-magento#152]
Yesterday I was excited to configure an see the great speed of jobrunner.

Later in the day however, I found that wkhtmltox rendered email/reports/quotation tests would fail after the jobrunner setup.

"wkhtmltopdf error -11)

When returned to the "pre jobrunner" situation report rendering worked again.
Running with Workers = 1 .  1 Gb Ram (have been able to run on 512mb)

Any thoughts on how to get them cooperating?

**Comment by guewen** [comment]
Was `--workers` set to `0` (threading-mode) before your changes and set to more than `0` (multiprocess) after?

When Odoo runs in threading-mode, it ignores the memory limits (`limit_memory_soft` and `limit_memory_hard`).

The error you had could be that now the memory limits are enforced and the generation of the report exhausted more memory than allowed by `limit_memory_hard` so the process was killed.

Try rising `limit_memory_hard`.

**Comment by l-arnold** [comment]
Thank you Guewen.  I thought was related to memory but little info in the error or on the web (got one report of similar from wkhtmltopdf folks)..  I will report back with findings (assuming I get there)

**Comment by l-arnold** [comment]
Had to quite significantly increase RAM memory limits but was able then to render email.  I assume bigger reports should also work (?)  

Moved the VM to 2 GB Ram (was running at 1gb and could run at 512mb)

Gave Odoo on openerp-server.conf

workers = 2 (was workers = 1)
limit_memory_hard =  1730150400  
was                               805306368

limit_memory_soft =     943718400 
was                               671088640

**Comment by l-arnold** [comment]
Workers were set to 1 and updated to 2 .  Before jobrunner was setup however,  workers = 0
