### ISSUE TITLE
Magento>>Odoo8 sales order import problem

### ISSUE THREAD

**Issue by atekkanat** [OCA/connector-magento#153]
Hi

I have installed this connector all like in this link: http://odoo-magento-connector.com/guides/installation_guide.html#magento.

I use Odoo 8 and Magento 1.9.2.1.

I can import all customer, customer group, produts category, products, quantity but I can not import sale order from magento.

I defined shipping (delivery methods as below picture. I use flat rate shipping on Magento.

![delivery](https://cloud.githubusercontent.com/assets/6152362/10363864/d40a4c70-6dbf-11e5-9eb4-912be94c6d3b.jpg)

I defined payment methods on Odoo like this. I used Magento Check / Money Order options on sales.
![paymnwt](https://cloud.githubusercontent.com/assets/6152362/10363924/309da4c8-6dc0-11e5-83c5-017ca611a0c1.jpg)

But when I click the import sales order button, all jobs created, worked without any errors but sales order did not imported.

Before
![import](https://cloud.githubusercontent.com/assets/6152362/10364103/5e688bec-6dc1-11e5-8964-a0f085522cf1.jpg)

After
![check](https://cloud.githubusercontent.com/assets/6152362/10364115/725d3cd8-6dc1-11e5-947e-e9afc1579ca8.jpg)

ANd chech point and also no sales order on SALES.
![import2](https://cloud.githubusercontent.com/assets/6152362/10364106/6398d338-6dc1-11e5-9be9-0d6042780804.jpg)

Could you help what I need to do work with import sales order from Magento?

Thanks

**Comment by guewen** [comment]
The jobs are paid, are you sure that your sales orders are not imported? Did you check both in "Quotations" and "Sales Orders" without any search filters?

As the field `Days before cancel` is 30 and the sales orders are imported only when paid, if your sales orders are unpaid after 30 days, they won't be imported. could you check this scenario?

**Comment by atekkanat** [comment]
I changed Days before cancel to zero and immidiate payment. Now I can see on order on Quotations tab without any any search filters. But how can I see on sales order menu without Quotations?

Thanks,

**Comment by guewen** [comment]
You have to confirm the sales orders, or activate the option "confirm sales orders" on the Automatic workflow.

**Comment by atekkanat** [comment]
Ok. Thanks for quick help. It works well.

Is This module only import from magento to odoo? can we import products and categoris from odoo to magento ?

Thanks

**Comment by guewen** [comment]
> Is This module only import from magento to odoo?

Yes

> can we import products and categoris from odoo to magento ?

No. At least not yet. And it could never be a complete syncronization because Magento supports many more features than Odoo for products (bundle products, options, custom attributes based on attribute set, ...).

**Comment by atekkanat** [comment]
OK. Thank you for really good module.

I appriciate...
