### ISSUE TITLE
Patch SUPEE-6788 Magento

### ISSUE THREAD

**Issue by autoslide** [OCA/connector-magento#162]
Hello all,
When I test the modules that cause problems with the new patch Magento, there is a problem with the connector Odoo / magento , do you have any recommendations to the update?

Regards

**Comment by jaredkipe** [comment]
Well it appears to me that the only admin route that exists now hasn't been needed since 1.3.x

So most likely, the route can go, and the controller can go.

**Comment by autoslide** [comment]
Thank you for answering and I see that everything is working properly .

Regards
