### ISSUE TITLE
step by step

### ISSUE THREAD

**Issue by Top-CMS** [OCA/connector-magento#169]
Hi,

Is there a simple tutorial available for install Magento Connector on Odoo 9?

I have a clean install of Odoo 9 on Ubuntu and that works great.

I did the steps http://odoo-magento-connector.com/guides/installation_guide.html, but I can't install the Magento Connector 

```
You try to install module 'connector_ecommerce' that depends on module 'connector'.
But the latter module is not available in your system.
```

Is told me to migrate the module to 9. But I am stuck on it, don't know exactly which module(s) need to migrate. 
Is there a simple way to install the Magento Connector or is there a good tutorial ?

Thnx

**Comment by l-arnold** [comment]
My understanding is that the Connector is working for Branch 8.0 but much of the system is not yet ported to Branch 9.0.  

Please look at the ReadMe.

I would recommend a Install of Odoo 8.0 along with the Connector Branch 8.0.  Others may have other information this way.

**Comment by Top-CMS** [comment]
So at this moment there is no working branche for Odoo 9 --- Magento Connector --- Magento 1.9.2.2?

**Comment by guewen** [comment]
@Top-CMS I think I already answered to this on #166. The connector has not been migrated for Odoo 9.0, so there is no way to install it. There is a great amount of work to do before being able to install it.
If you need it right now, I would recommend to install the 8.0 version. Please also be aware of https://www.indiegogo.com/projects/odoo-connector-odoo-magento-connector-for-odoo-9/x/2127924#/

**Comment by Top-CMS** [comment]
Okay..thanks
