### ISSUE TITLE
[8.0] taxes are not imported on orderlines

### ISSUE THREAD

**Issue by haroldtamo** [OCA/connector-magento#184]
When importing orders from magento, taxes are not writed on orderlines.

**Comment by haroldtamo** [comment]
When importing orders, the connector doesn't include taxes on orderlines. 

The documentation (http://odoo-magento-connector.com/howto/configure_taxes.html) says that taxes are excluded by default on product and orderlines.

How can i import taxes on orderlines ?

**Comment by guewen** [comment]
Hello,

The taxes set on order lines are the taxes setup on your Odoo products.

## 

Guewen Baconnier
Business Solutions Software Developer

Camptocamp SA
PSE A, CH-1015 Lausanne
Phone: +41 21 619 10 39
Office: +41 21 619 10 10
http://www.camptocamp.com/

**Comment by haroldtamo** [comment]
if I understand well I have to set a tax per product in Odoo?

I set a tax on a product in magento but on import, the tax is not imported (I also check in the ProductImportMapper and there is no mapping for the tax field)

I thought that the tax set on a magento product will be easily imported in odoo. Is there a specific  reason for the lack of a tax mapping in ProductImportMapper ?

**Comment by haroldtamo** [comment]
Ok thanks for the answer but what about tax classes ? I explain : 

In magento, we have rules like, if the customer is from a specific country, we don't put a tax on order even if there is a tax on product.

If i set a default tax on a product in odoo , there will be a tax set on orderline in odoo, what is not the case in magento (in that case).

Have you already find a way to handle that ?

Thanks.

**Comment by guewen** [comment]
> In magento, we have rules like, if the customer is from a specific country, we don't put a tax on order even if there is a tax on product.

Here is one of the reason why it is difficult to synchronize taxes.

> Have you already find a way to handle that ?

Yes, you should use the modules from the [account-fiscal-rule project](https://github.com/OCA/account-fiscal-rule/)

**Comment by haroldtamo** [comment]
OK.
Many thanks for your help :+1: .

PS : Is there a doc on how to use the account-fiscal-rule project ? (I google with no relevant answer :( )
