### ISSUE TITLE
pending state

### ISSUE THREAD

**Issue by mehulbhadra** [OCA/connector-magento#186]
![screenshot from 2015-12-18 19 03 14](https://cloud.githubusercontent.com/assets/16115826/11897988/48e2f02e-a5ba-11e5-9790-4ada2b5d7f2f.png)
when i click button in odoo backend its jobs are always in pending state....

**Comment by sschuchlenz** [comment]
+1 (odoo v8, magento 1.9.x)

I already tried to use --workers=4 and rely on `connector`'s jobrunner (setting all the options and disabling `Enqueue Jobs`) but no luck with that either. I'm using a multi-database install and synchronizing metadata works fine, only when I add one of the background jobs in `Magento -> Backends` the job never gets executed.

Whenever I try to reschedule a job, the `Enqueue time` stays empty. Logfile does not give any errors and other jobs (like fetching email) work fine.

**Comment by sschuchlenz** [comment]
Could someone please have a look and provide assistance? This is a dealbreaker since we need the sync between Magento and Odoo for our business. Thank you in advance.

**Comment by guewen** [comment]
Metadata sync is done synchronously, it doesn't use the jobs.
Jobs staying pending means you have no job runner started.
If you hadn't yet, have a look on http://odoo-connector.com/guides/jobrunner.html
If you think you already did what this page says, please give details on your configuration (what command you run to start Odoo, your `connector` revision, what contains your odoo configuration file)

**Comment by sschuchlenz** [comment]
I configured the jobrunner part as mentioned in the link you provided (thanks for the answer) and since there are no errors in the log I reckon it is working as it should.

Here is my odoo start script: http://pastebin.com/SLNerb4w

The versions of the magento connector and its dependencies are the latest git commits from the 8.0 branches.

**Comment by sschuchlenz** [comment]
Update: I just checked the logfile again, it says:

```
2015-12-31 10:17:13,168 4113 INFO ? openerp.addons.connector.jobrunner.runner: starting
2015-12-31 10:17:13,168 4113 INFO ? openerp.addons.connector.jobrunner.runner: initializing database connections
2015-12-31 10:17:13,195 4113 INFO ? openerp.addons.connector.jobrunner.runner: database connections ready
```

This tells me that the jobrunner _should_ be running I guess, but the line from the link you provided is missing:

`...INFO...connector.jobrunner.runner: connector runner ready for db <dbname>`

Is this due to the fact that we're running a multiple database environment? Is there a way to specify which databased the jobrunner should "take into account"?

**Comment by sbidoul** [comment]
Ok, almost there. The jobrunner is starting but not connecting to your database.

Since you have %d in your dbfilter, you need https://github.com/OCA/connector/pull/166 or https://github.com/OCA/connector/pull/165.

**Comment by sbidoul** [comment]
> Is there a way to specify which databased the jobrunner should "take into account"?

The connector currently tries to use dbfilter to determine which databases to connect to. But that will probably be removed in the next major release, so connector will connect to all databases where `connector` is installed, much like the Odoo cron scheduler which is running on all available databases (unless the `db_name` option is used).

**Comment by sschuchlenz** [comment]
That did it - thank you very much for your support, especially over the holidays!

**Comment by mehulbhadra** [comment]
Import is working properly from magente to odoo..can we export product from
odoo to magento

On Sat, Jan 2, 2016 at 2:56 PM, sschuchlenz notifications@github.com
wrote:

> That did it - thank you very much for your support, especially over the
> holidays!
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/OCA/connector-magento/issues/186#issuecomment-168375102
> .

## 

Thanks,
Mehul Bhadra

**Comment by guewen** [comment]
See https://github.com/OCA/connector-magento/issues/188.
