### ISSUE TITLE
wrong website_id (magentoerpconnect_pricing)

### ISSUE THREAD

**Issue by tomwic** [OCA/connector-magento#190]
Hi,

The module magentoerpconnect_pricing report wrong date format:

File "/root/connector-magento-8.0a/magentoerpconnect/unit/export_synchronizer.py", line 100, in _should_import
MAGENTO_DATETIME_FORMAT)
File "/usr/lib/python2.7/_strptime.py", line 325, in _strptime
(data_string, format))
ValueError: time data '2015-12-30 21:26:51' does not match format '%Y/%m/%d %H:%M:%S'

It is because it refer to wrong website_id. In below case it should be 4 instead of 5.

openerp.addons.magentoerpconnect_pricing.product.export_product_price('magento.product.product', 579, website_id=5)

website_id: 5 - de_DE, 4 - en_GB.

Br, Tomek

**Comment by guewen** [comment]
Hi,

Thanks for your report but it doesn't help me to understand how website_id is wrong. Can you show the content of the table `magento.website` and why you expect the website_id to be 4 instead of 5?

**Comment by guewen** [comment]
Are you sure the datetime error is related to the `website_id`?

**Comment by tomwic** [comment]
Hi,

not sure. I've setted different locale settings per websites and nothing changed means does not work for all cases.

I did some investigation:
1. https://robotsystematic.com/format-date-magento
Short: 30-10-13 but it could be change under: System>Config>Sales>Calalog>Date&Time Custom 
Options, + extend year to 4 digits format.
but It always use hypen '-' not slash '/'. 

I found that in magentoerpconnect/unit/backend_adapter.py that we have:
MAGENTO_DATETIME_FORMAT = '%Y/%m/%d %H:%M:%S'

Br, Tomek

**Comment by tomwic** [comment]
also found that "They are converted from the format corresponding to your admin locale to the standard mysql format (YYYY-mm-dd)." on magento side.

**Comment by guewen** [comment]
The date format issue is #188.

The website_id issue is this report. I don't think there is a relation.

Regarding the `website_id`, I still don't have enough information to understand the bug.

**Comment by tomwic** [comment]
How I can send you some screen shoots from configurations both: magento and odoo?

**Comment by guewen** [comment]
you can post them here, just be sure to hide confidential data

**Comment by tomwic** [comment]
I checked in Odoo database that website-id is correct.

How to fix the problem with date?
