### ISSUE TITLE
[Question] Automatic invoice validation

### ISSUE THREAD

**Issue by azeemism** [OCA/connector-magento#192]
One of the core features listed for the connector-magento is automatic invoice validation. 

Will installing the OCA account invoicing modules for Odoo (https://github.com/OCA/account-invoicing), that adds a validation step on invoicing process, cause an issue with the connectors ability to automatically validate invoices?

Thanks

**Comment by guewen** [comment]
The automatic invoice validation is part of the [sale_automatic_workflow](https://github.com/OCA/sale-workflow/tree/8.0/sale_automatic_workflow) addon. For the validation of the invoice, it sends the workflow signal `invoice_open`, so I guess that if the module adding a steps do not override this workflow's behavior, the invoice will still be open.
