### ISSUE TITLE
[Question] Why filter orders by state and not by status

### ISSUE THREAD

**Issue by danielozano** [OCA/connector-magento#193]
Hi, first of all sorry for my english.
I have a question. Why openERP filters orders by state and not by status?

Maybe it's and issue of our custom extension installed for credit payments on Magento (so Im sorry), but I would like to understand why state instead of status (and know the correct workflow).

For example if you pay with credit card, when you enter the TPV, a new order is created with:
- state = new 
- status = canceled (I configured it for that)

But if the client exits the tpv and he doesnt come back to the site, the order state remains as new and status = canceled, so when I import sale orders to openERP, these incorrect sale orders are imported.

Thats because I dont fully understand why openERP filters by state and not by status when you import the orders.

Im not an expert so maybe im asking nonsense.

Tank you so much.

**Comment by guewen** [comment]
Because AFAIK, states are always the same on every installation, but status vary widely. So it is up to you to create a customization addon (http://odoo-magento-connector.com/guides/tutorial_customize.html) and override the part which search for the sales orders in the sales importer.

**Comment by danielozano** [comment]
Nice thank you so much.
