### ISSUE TITLE
Odoo Mangeto connector / stock synchronization / incorrect quantities

### ISSUE THREAD

**Issue by tomwic** [OCA/connector-magento#226]
Hi,

in principle in description of connection is written that it is bidirectional connector. 

Its true but I found situation that:

I have stock quantities of product = 5 pcs.
-->total stock quantity for this product is 5 (odoo)
-->total stock quantity for this product is 5 (magento)

after placing two order A&B in magento we have:
(with 1 pcs for each order)

order A, with product - 1 pcs.
order B, with product - 1 pcs.

total stock quantity for this product is 3 (magento)

in odoo

orders are imported but products are not reserved yet

-->total stock quantity for this product is 5 (odoo)
-->total stock quantity for this product is 3 (magento)

after pick up product for order A we have:

-->total stock quantity for this product is 4 (odoo)
and after export stock quantity by connector
-->total stock quantity for this product is 4 (magento, correct value is 3) 

after pick up product for order B we have:

-->total stock quantity for this product is 3 (odoo)
and after export stock quantity by connector
-->total stock quantity for this product is 3 (magento)

in meantime between pickup product between order A and order B we have incorrect
quantity in magento.

Please comment if it is correct behaviour or its configuration error and how to fix it.

Best regards,
Tomek

**Comment by StefanRijnhart** [comment]
The pushed stock level certainly does depend on your configuration. Do you import your orders as confirmed or as draft orders? What stock qty field are you exporting (default = virtual qty). If you export virtual quantity, and you import your orders as draft, then you have the phenomenon that you describe. Virtual quantity in Odoo is updated at order confirmation time rather than at picking time.

**Comment by tomwic** [comment]
I use quantity on hand because some products have very long delivery time.
Visitual stock is quantity on hand + incoming quantity - outgoing quantity 
but I need
quantity on hand  - (outgoing quantity + outgoing quantity for open sales)

**Comment by StefanRijnhart** [comment]
Yes, in that case the quantity is only deducted when the product is shipped. You would need to implement a custom stock field for your purposes.

**Comment by tomwic** [comment]
what decide how orders are imported: as draft or as confirmed ?

**Comment by StefanRijnhart** [comment]
You can configure order confirmation on the (automatic) workflow that is linked to each of your payment methods.

**Comment by tomwic** [comment]
the module https://www.odoo.com/apps/modules/8.0/stock_available/ help us to fix this issue.
