### ISSUE TITLE
Imported orders not visible

### ISSUE THREAD

**Issue by antonio-valdez-arce** [OCA/connector-magento#241]
Hello there,
The short description of the problem is: The imported orders from the Magento shop are not listed in the sales orders list in Odoo.

Details of my installation:
- Magento version: 1.9.2.4
- Magento Extensions: 
        **Bubble API** (https://github.com/jreinke/magento-improve-api)
        **OpenLabs OpenERPConnector** (https://www.magentocommerce.com/magento-connect/magento-connector-for-openerp.html)
- Odoo 8.0-20160430
- OCA connector-magento (of course)

So I have some orders in my shop, and I want to import them into Odoo using the connector. Here are the steps I do:

**1. Request the sales orders synchronisation:**

In Odoo, go to the menu "Connectors -> Storeviews" and select the store view that you want to import from. In my case it was the Italian store view, where I placed an order:
<img width="826" alt="screen shot 2016-10-19 at 16 45 59" src="https://cloud.githubusercontent.com/assets/3852403/20431633/594e8ff6-ad9b-11e6-9779-2b2b8e0f1cd1.png">

Then click the "Import Sale Orders" button to import the orders from Magento:
<img width="943" alt="screen shot 2016-10-19 at 16 46 13" src="https://cloud.githubusercontent.com/assets/3852403/20431669/96442484-ad9b-11e6-9f8f-911a41ecfd22.png">

**2. Check for the status of the synchronisation in the Jobs queue:**

Immediately check the job created by the step 1, going to the menu "Connectors -> Jobs", you can see that there is a job record containing the ID if the test order done in Magento:
<img width="1670" alt="screen shot 2016-10-19 at 16 36 28" src="https://cloud.githubusercontent.com/assets/3852403/20431691/bab26326-ad9b-11e6-8722-8886d92eb40d.png">
First it will be with status "Pending", but after some moment it will be executed and changed to "Done".

3. Check the order I made in the Magento shop side:

When step 2 is completed, click on the Job to see the details:
<img width="1144" alt="screen shot 2016-10-19 at 16 37 03" src="https://cloud.githubusercontent.com/assets/3852403/20431755/074b0ae4-ad9c-11e6-8e61-3d99754f97c9.png">
The job was done without errors.

4. Check for the Sale Orders list in Odoo, but it's empty:

Even if the import didn't have any errors, I can't find any Sale Order in the list. To see the list, go to "Sales -> Sales Orders" and the list will be empty:
<img width="967" alt="screen shot 2016-10-19 at 16 39 09" src="https://cloud.githubusercontent.com/assets/3852403/20431775/252ef08e-ad9c-11e6-9b08-b3fc3ff6a312.png">

I'm not a Python developer so I can't really debug the Odoo installation.
I made a tetst of the Magento SOAP API and the data of the orders are returned to Odoo correctly.

Could you help with this problem?

Thanks in advance.

Antonio Valdez

**Comment by pedrobaeza** [comment]
Have you looked into quotations?

**Comment by antonio-valdez-arce** [comment]
Hello Pedro!
You're right! the sale orders are in the quotations section. So it's not an issue. 
Thank you for the quick response!
