### ISSUE TITLE
[8.0]  Wrong value for ir.module.module.license  'LGPL-3' ?

### ISSUE THREAD

**Issue by haroldtamo** [OCA/connector-magento#244]
I recently pull the latest version of connector and all his dependencies, but when I upgrade the module magentoerpconnect, the error above is shown.

In source code, only e-commerce module is under LGPL-3 and it's not even installed. 

What could cause that ?

**Comment by pedrobaeza** [comment]
You have to update your Odoo code base.

**Comment by haroldtamo** [comment]
thanks pedro. did you mean all the other files outside  the addons folder? It's true that i avoid updating them but i will do as you said
