### ISSUE TITLE
Server environment module

### ISSUE THREAD

**Issue by kkoci** [OCA/connector-magento#246]
Hi, trying to install one of the magento's modules, I encounter an issue, which is a module I don't have, and can't find anywhere.

It's called 'server_environment'

Any clues on where can I find it?

**Comment by pedrobaeza** [comment]
It's on OCA/server-tools.

**Comment by kkoci** [comment]
Just saw it, weird, because when cloning from console it didn't get it

Anyways, Thank You very much
