### ISSUE TITLE
Recent sale orders are not fetched from Magento if the server's timezone is greater than UTC

### ISSUE THREAD

**Issue by iurii2017** [OCA/connector-magento#249]
Hi all,

I've recently setup magentoerpconnect at my local Odoo 8.0 instance and faced the next problem:
* Orders that I created in Magento recently (15 minutes ago for example) are not picked up by the import job while old orders are imported fine
* My timezone is UTC+2

The possible cause of the issue is in the file `magentoerpconnect/magento_model.py`, method `import_sale_orders(self)`
* The line is `import_start_time = datetime.now()`
* This start time is treated as UTC while it's actually in UTC+2
* In the end of the execution of the method this value is stored as `import_orders_from_date` into DB. And during the next job run it will be picked as a `from_date` (which is effectively shifted by two hours). Magento treats that timestamp as UTC and as a result does not find an order

The solution that worked for me is to change that line to be `import_start_time = datetime.utcnow()`

**Comment by guewen** [comment]
Hi, by design, `ntp` should be installed on both servers, and both servers work with UTC (http://odoo-magento-connector.com/guides/installation_guide.html#requirements-on-both-servers).
