### ISSUE TITLE
connector-magento with Odoo v.10

### ISSUE THREAD

**Issue by MakMas** [OCA/connector-magento#250]
Hello,
Its mins that connector works with Odoo 10?

Odoo Connector Magento Modules

Odoo Magento Connector (also known as MagentoERPconnect) is a bi-directional connector, 100% compatible with the last OpenERP 10.0 and latest Magento versions (1.x).

**Comment by shurper** [comment]
I join the issue.

**Comment by guewen** [comment]
You are welcome to test and review #255
