### ISSUE TITLE
please tell me step how to install

### ISSUE THREAD

**Issue by rivelta** [OCA/connector-magento#257]
i have been confused all related the odoo connector , i cant run correctly . and i have been placed on add on magento folder. 
and my questions :
1. how i can find odoo connect configuration on this module
2. how i can get setting for server_enviroment_files
3. i have been follow http://odoo-magento-connector.com/
instructions , but no work and i frustated. no one give correct guide
4. how i can setting magento api for connecting odoo?

all remain guide its all not clear...

**Comment by rivelta** [comment]
im using odoo connector v8 ( magento 1.70.2 and odoo 8.0 )

**Comment by guewen** [comment]
See https://github.com/OCA/connector-magento/issues/139#issuecomment-325281683
