### ISSUE TITLE
External ID not found in the system: base.menu_config"

### ISSUE THREAD

**Issue by thomas-thaulow** [OCA/connector-magento#258]
Hello, downloaded the Odoo connector into apps folder, and changed all _manifest files to install true. Tried then installing but gives me this error: 

ParseError: "External ID not found in the system: base.menu_config" while parsing /var/www/erp/odoo/addons/connector/setting_view.xml:44, near
<menuitem id="menu_connector_config_settings" name="Connector" parent="base.menu_config" sequence="20" action="action_connector_config_settings"/>

Any idea how to fix?

**Comment by pedrobaeza** [comment]
That's because the module is not yet migrated. See https://github.com/OCA/connector-magento/pull/255 for the work on the migration.

**Comment by thomas-thaulow** [comment]
Shoudlnt the description be updated then? 
"Odoo Magento Connector (also known as MagentoERPconnect) is a bi-directional connector, 100% compatible with the last OpenERP 10.0 and latest Magento versions (1.x)." 

Also how is the pull request doing, is it running?

**Comment by pedrobaeza** [comment]
That description is automatic, but just below it you can see the list of unported modules. About the pull request, just try yourself and check the status in the comments.

**Comment by thomas-thaulow** [comment]
You try to install module 'connector_magento' that depends on module 'base_technical_user'.
But the latter module is not available in your system. 

Any idea where I find that module?

**Comment by pedrobaeza** [comment]
https://github.com/OCA/server-tools/tree/10.0/base_technical_user

**Comment by thomas-thaulow** [comment]
Ok #255  gives me same error for "External ID not found in the system: base.menu_config"

Is any of the Magento 10 connectors for sale out there any good? I guess this edition wont be running for a while...

**Comment by pedrobaeza** [comment]
I think you are not installing it correctly and you will find similar problems with a purchased connector. Start again with a fresh installation, and make sure you put the proper code in it, with all the dependencies.

**Comment by thomas-thaulow** [comment]
But you just said "That's because the module is not yet migrated. See #255 for the work on the migration." and now you say its because I installed wrong?

**Comment by pedrobaeza** [comment]
They are complementary: use right code and install it properly.

**Comment by thomas-thaulow** [comment]
New install gave me 

File "/usr/lib/python2.7/site-packages/odoo/models.py", line 1083, in _validate_fields
    raise ValidationError("%s\n\n%s" % (_("Error while validating constraint"), tools.ustr(e)))
ParseError: "Error while validating constraint

View inheritance may not use attribute 'string' as a selector.

Error context:
View `product.normal.form`
[view_id: 1148, xml_id: n/a, model: product.template, parent_id: 385]
None" while parsing /var/www/erp/odoo/addons/product_m2mcategories/views/product_view.xml:4, near
<record id="product_normal_form_view_add_categids" model="ir.ui.view">
            <field name="name">product.normal.form</field>
            <field name="model">product.template</field>
            <field name="inherit_id" ref="product.product_template_form_view"/>
            <field eval="7" name="priority"/>
            <field name="arch" type="xml">
                <xpath expr="//page[@string='Information']" position="after">
                    <page string="Extra Categories">
                        <group string="Classification Categories" name="classification_categories">
                            <field name="categ_ids" nolabel="1" colspan="2"/>
                        </group>
                    </page>
                </xpath>
            </field>
        </record>

**Comment by guewen** [comment]
@CiaraCode `product_m2mcategories` is not a requirement of `connector_magento` in v 10.0. The module is named `product_multi_category` and is in https://github.com/OCA/product-attribute
I don't know what is trying to install  `product_m2mcategories` in you setup.

**Comment by thomas-thaulow** [comment]
@guewen, thats strange. I have a fresh install of Odoo 10, and only downloaded the Odoo connector module from github... :/

**Comment by guewen** [comment]
I think you are trying to install the code from the 10.0 branch https://github.com/OCA/connector-magento/tree/10.0/magentoerpconnect, but this module is not yet migrated. You have to use the branch from https://github.com/OCA/connector-magento/pull/255 (which is https://github.com/guewen/connector-magento/tree/10.0-components)

**Comment by thomas-thaulow** [comment]
Used the latest revision you uploaded for 2 hours ago @guewen , from the https://github.com/guewen/connector-magento/tree/10.0-components link. 

When trying to install module, i get this error: 

ParseError: "duplicate key value violates unique constraint "mail_followers_mail_followers_res_partner_res_model_id_uniq"
DETAIL:  Key (res_model, res_id, partner_id)=(sale.order, 9, 3) already exists.
" while parsing /var/www/erp/odoo/addons/sale/data/sale_demo.xml:17, near
<record id="sale_order_1" model="sale.order">
            <field name="partner_id" ref="base.res_partner_2"/>
            <field name="partner_invoice_id" ref="base.res_partner_2"/>
            <field name="partner_shipping_id" ref="base.res_partner_2"/>
            <field name="user_id" ref="base.user_demo"/>
            <field name="pricelist_id" ref="product.list0"/>
            <field name="team_id" ref="sales_team.team_sales_department"/>
            <field name="date_order" eval="(DateTime.today() - relativedelta(months=1)).strftime('%Y-%m-%d %H:%M')"/>
        </record>

**Comment by guewen** [comment]
@CiaraCode This error happens in the core sale's module, and in the demo data besides that. Did you really mean to install demo data? Was it a fresh database? It's seems it is corrupted...

**Comment by thomas-thaulow** [comment]
I have replaced all files and new database, now it seems to allow me further. But I do have issues with "Unable to install module "component" because an external dependency is not met: No module named cachetools" 

Not quite sure what it means by external dependency, and did not find any "cachetools" files in any OCA branches. Would I need to specify a caching mechanism in odoo?

**Comment by guewen** [comment]
> Not quite sure what it means by external dependency, and did not find any "cachetools" files in any OCA branches. Would I need to specify a caching mechanism in odoo?

This is a python egg. It could be `pip install cachetools`, but it depends how you usually install your python dependencies.

**Comment by thomas-thaulow** [comment]
Finally worked! :) For Magento, is $ bzr branch lp:magentoerpconnect/magento-module-oerp6.x-stable magento-module this the latest module available? 

Also any other options to install module without bazaar?

**Comment by guewen** [comment]
> Finally worked! :)

Hooray!

> For Magento, is $ bzr branch lp:magentoerpconnect/magento-module-oerp6.x-stable magento-module this the latest module available?

Yes


> Also any other options to install module without bazaar?

Not that I know of. But yeah, this is not convenient.

**Comment by thomas-thaulow** [comment]
Could someone be kind enough to upload the module as zip for me? :/ I can even host the file if no one wants to, a magento module is so simple its no reason not to just zip it :p

**Comment by l-arnold** [comment]
Ciara, 

These are some old notes on my side. I expect the main instructions are complete but the Magento module I know is tricky. 

You may look at the following for the Magento module. 

https://github.com/openlabs/magento 

https://www.magentocommerce.com/magento-connect/magento-connector-for-openerp.html 

On the Magento Python package my method for install in debian Jessie WAS 

apt-get install python-pip 
then 
pip install magento 

I would need to go do a new install to get the proper context on the above. Its been a few years since I last installed. 
I want to do a test bed for Version 10 so I can be a proper tester. 

I hope this brings some context anyway.. 

Landis

**Comment by l-arnold** [comment]
Ciara, 
Easiest to do as the instructions read though. 
You do need to install BZR 

apt-get install bzr 
or 
apt install bzr 
(depending upon your Magento system) 

(then follow the instructions below) 
from: http://odoo-magento-connector.com/guides/installation_guide.html 
Magento [ http://odoo-magento-connector.com/guides/installation_guide.html#magento | ¶ ] 


For the time being, the Magento extension originally built by OpenLabs is still used by the connector. But the version published on Magento Connect is outdated. 

Download the following Bazaar branch and install it in Magento: 
$ bzr branch lp:magentoerpconnect/magento-module-oerp6.x-stable magento-module 


In order to install it: 

    1. Move the Openlabs folder in the magento_root/app/code/community . 
    2. Move the file app/etc/modules/Openlabs_OpenERPConnector.xml in magento_root/app/etc/modules . 
    3. Flush the Magento cache from the admin panel or by removing everything in magento_root/var/cache 

(also, the Magento Python Package install referenced in the last message below I recall to be on the Odoo system as it is running Python and Magento runs PHP) 

Hope that helps. 
Landis 

Landis Arnold

**Comment by thomas-thaulow** [comment]
Should I use https://www.mysite.com/api/v2_soap/?wsdl=1 in "Location"  config? 

I tried both with V1 and V2 soap api url, but I only get: 

"Check your configuration, we can't get the data. Here is the error:
ResponseError()"

**Comment by guewen** [comment]
@CiaraCode Only https://www.mysite.com

**Comment by thomas-thaulow** [comment]
@guewen Check your configuration, we can't get the data. Here is the error:
<Fault 3: 'Invalid api path.'>

**Comment by thomas-thaulow** [comment]
Managed to fix! But should "Admin" be a store, store-view and website in odoo?

**Comment by guewen** [comment]
> But should "Admin" be a store, store-view and website in odoo?

IIRC it's the case in Magento too (but perhaps it is hidden on its UI).
