### ISSUE TITLE
New connector_magento support for Magento 2

### ISSUE THREAD

**Issue by samy-m-dev** [OCA/connector-magento#272]
Since magentoerpconnect was changed to connector_magento, big thanks to @guewen . Is there any plan to make it compatible also with Magento 2?

There's a branch here available on https://github.com/OCA/connector-magento/issues/211 , thanks to @StefanRijnhart but it's based on old magentoerpconnect.

**Comment by saxomanu** [comment]
Hi, i'm working on support for magento2 odoo v10 based on 10-component of @guewen work. https://github.com/saxomanu/connector-magento/tree/10.0-components-magento2/connector_magento

**Comment by flotho** [comment]
@StefanRijnhart , I thinks that this one could be close because of duplicate https://github.com/OCA/connector-magento/issues/211

**Comment by pedrobaeza** [comment]
Yes, closing.
