### ISSUE TITLE
Versioning in the new connector api

### ISSUE THREAD

**Issue by iledarn** [OCA/connector-magento#275]
In prior version of the api I could use versioning - for example, use different implementation of importers depending on the version of my backend:

> @bmw                                                                                                                                                                                              
> class BMWPartImporter(CSVPartImporter):                                                                                                                                                           
>     _category_key = 'Categories'                                                                                                                                                                  
>     _fitment_key = ['Vehicle']                                                                                                                                                                    
>                                                                                                                                                                                                   
>                                                                                                                                                                                                   
> @ducati                                                                                                                                                                                           
> class DucatiPartImporter(CSVPartImporter):                                                                                                                                                        
>     _category_key = 'Category'                                                                                                                                                                    
>     _fitment_key = ['Family', 'Model', 'Year']

How to do the same in the current api? Should I use the ``_collection`` attribute for this? Please give me an example

**Comment by guewen** [comment]
Hello, please read the migration guide: http://odoo-connector.com/guides/migration_guide.html#backend-versions

For instance:

```python

class MotorcyclePartImporter(CSVPartImporter):

    _categories = {'bmw': 'Categories', 'ducati': 'Category'}
    _fitments = {
        'bmw': ['Vehicle'], 
        'ducati': ['Family', 'Model', 'Year'],
    }

    @property
    def _category_key(self):
        return self._categories[self.backend_record.brand]

    @property
    def _fitment_key(self):
        return self._fitments[self.backend_record.brand]
```

You could also use a factory component which would return you the correct one.

```python

class MotorcycleImporterFactory(Component):
    _name...

    _components = {
         'bmw': 'bmw.importer',
         'ducati': 'ducati.importer'
    }
    def get_component(self, brand):
        return self.component(usage=self._components[brand])
        
 class BMWPartImporter(CSVPartImporter):
    _name...
    _usage = 'bmw.importer'
    _category_key = 'Categories'
    _fitment_key = ['Vehicle']

class DucatiPartImporter(CSVPartImporter):
    _name...
    _usage = 'ducati.importer'
    _category_key = 'Category'
    _fitment_key = ['Family', 'Model', 'Year']

```

Or implement a custom matcher:

```python

 class BMWPartImporter(CSVPartImporter):
    _name...
    _usage = 'motorcycle.importer'
    _category_key = 'Categories'
    _fitment_key = ['Vehicle']

    def _component_match(cls, work):
        return work.collection.brand == 'bmw'

class DucatiPartImporter(CSVPartImporter):
    _name...
    _usage = 'motorcycle.importer'
    _category_key = 'Category'
    _fitment_key = ['Family', 'Model', 'Year']

    def _component_match(cls, work):
        return work.collection.brand == 'ducati'
```

**Comment by iledarn** [comment]
I have used the custom matcher variant.
Observation: ``_componen_match`` should be decorated with ``@classmethod``

**Comment by guewen** [comment]
> I have used the custom matcher variant.
> Observation: _componen_match should be decorated with @classmethod

Sure. I wrote the examples from the top of my head.

You're welcome.
