### ISSUE TITLE
Magento Odoo

### ISSUE THREAD

**Issue by shingi991** [OCA/connector-magento#315]
Hi, having issues with syncing my magento to odoo, aswell as product categories.. Can anyone Gove ideas on how to deal with issue.? Magento2 to odoo13

**Comment by joosuavip** [comment]
Hello @shingi991, can you give a more detailed description of the issues you're having?

**Comment by shingi991** [comment]
![Screenshot 2021-03-30 at 18 44 36](https://user-images.githubusercontent.com/79038879/113035267-58256d80-9193-11eb-9321-6a6c05a79e1f.png)

Im getting this error when I try send a response on my odoo helpdesk
