### ISSUE TITLE
magento connector in multi-company

### ISSUE THREAD

**Issue by chafique-delli** [OCA/connector-magento#32]
Hi,

We have a customer project with a single backend magento including several website and side Odoo it is multi-company.
I wanted to ask your opinion for import sale orders , either change the company for user  'administrator' using the company on the magento.store (thus sale.shop)  to execute scheduler or by adding a 'connector_user_id' m2o on company to a user and by switching to the user configured on the
company as explained here: https://www.mail-archive.com/openerp-connector-community@lists.launchpad.net/msg00091.html.

Regards,

**Comment by guewen** [comment]
Switch to another user is the proper solution if you want the properties to be applied correctly. Switching the company on the admin user would not allow concurrent tasks, it seems be error-prone.

**Comment by chafique-delli** [comment]
Ok, Guewen, thank you for your explanation.
