### ISSUE TITLE
[Feature] Payment methods linked with Storeview

### ISSUE THREAD

**Issue by kenvac** [OCA/connector-magento#56]
Hi,

It would be nice to link payment methods with storeview. When there are multiple shops with different currency, the sale_payment_method doesn't link with correct sale order. 

Consider a scenario:
### Magento Setup
- Europe Website
  - UK store
    - UK store view (GBP)
    - Payment method: Paypal
  - France Store 
    - France Store view (EUR)
    - Payment method: Paypal
  - Australia Store
    - Australia Store view (AUD)
    - Payment method: Paypal 
### openerp Setup
- UK company (Main company)
  - UK shop (Default currency GBP)
  - Euro Shop (EUR)
  - Australia Shop (AUD)
- Sale Payment methods
  - Paypal UK (UK company)
  - Paypal EUR (UK company)
  - Paypal AUD (UK company)

There is no way (am I missing something?) we can link Paypal AUD payment method to Australia store sale orders. 
#### Proposal
- Add new field shop_id on sale.payment.method object
- Modify payment mapping on order (magentoerpconnect/sale.py:921 def payment) and add shop_id in search filter 

I am open for suggestion. I would be amazed If this can be done without writing a single line of code.

Regards,
K

**Comment by guewen** [comment]
Hi,

You are right, there is nothing like that currently. It makes sense I think.

Thanks!

**Comment by kenvac** [comment]
obsolete
