### ISSUE TITLE
Support for Odoo

### ISSUE THREAD

**Issue by johnsh** [OCA/connector-magento#67]
Exists support  for Odoo V.8 now ?

Thanks

My English es Bad

**Comment by OSguard** [comment]
No

**Comment by johnsh** [comment]
Thanks for replying

I would recommend an option to communicate with an external application from Odoo

thank you very much

**Comment by OSguard** [comment]
this repository handle the integration between odoo<-> magento. For Odoo v8 is not start. For other integration their are some other repositories.
So can we close this issue?

**Comment by johnsh** [comment]
Ok, very thanks for your reply
