### ISSUE TITLE
Separate tax settings per storeview

### ISSUE THREAD

**Issue by mistotebe** [OCA/connector-magento#72]
It appears that Magento can have different settings for each storeview with regards whether tax is included in the price or not, which is a situation the connector cannot handle at the moment. Not sure if there is a way to find out what the setting is from magento through the API.

Proposed solution: add a checkbox (and a migration script to move the backend setting there) or a tri-state field (included/excluded/inherit from backend) on the storeview and update the code in SO import to check that instead.

What do you think?

**Comment by mistotebe** [comment]
If I go with the checkbox on storeview+migration script, what is the versioning policy of the module? Do changes like this bump the minor or major version (aka 2.4.3 or 2.5.0)? I'm going to guess 2.4.3, but making sure.

**Comment by guewen** [comment]
We can go with 2.5.0 as schema will change. Before the migration to GitHub, I used to merge all the things that change the schema in one "big" release (so 2.4.x to 2.5.0 for instance) and fixes that just needed to restart the server in a minor release (2.4.2 to 2.4.3). But now that the project is on GitHub with the merge one-click-button and that any committer within the OCA can push the button, it is more difficult to have true releases as merges are spread over time.

Regarding the change you propose, I am not the one with the most knowledge on tax include/exclude, but for what I know it makes sense. 

ping @rdeheele, can you confirm?

> Not sure if there is a way to find out what the setting is from magento through the API.

Worth to check but I would be surprised if it was possible ;-)

**Comment by mistotebe** [comment]
Talked to a person on our team who knows some magento and looks like getting that setting from magento is not (easily) possible.

**Comment by guewen** [comment]
So it has to be configured manually, that's not the first nor the last thing we won't be able to sync automatically with magento :-(

**Comment by rdeheele** [comment]
yes, this setting about tax inclusion seems not available through the API.
If the tax inclusion can vary according the storeview in Magento, it makes sense to be symetric in Odoo.
