### ISSUE TITLE
connector 8.0 sale shop object

### ISSUE THREAD

**Issue by fevxie** [OCA/connector-magento#79]
Hi, all
      For odoo 8.0 there didn't have sale shop model again,  user can set warehouse and pricelist directly on sale order.  connector for odoo v7 we use the sale shop as a bridge between sale order and magento store. 
for odoo 8.0 what should do for this relationship.  I'm pleasure to listen your opinions.

Best Regards

**Comment by guewen** [comment]
Hi,

I just sent you an email with some news and questions about the migration.

About the Sale Shop:

`magento.store` has an `_inherits` on `sale.shop`.

It probably needs more thoughts, but my first feeling is that:
- Remove the `_inherits`, `magento.store` will become a standalone model
- Move the fields (`warehouse_id`, ...) from `sale.shop` to `magento.store`,
  if necessary! We have to check if we need them (example: do I need to be
  able to change the warehouse if the magento store is different, yes I presume)
- Add mappings for the new fields of `magento.store` so they are set on new sales order
- Add a m2o on `magento.sale.order` to the `magento.store`

If you already have some work, please push your branches and create pull
requests with [WIP] in the title.

Thanks!

**Comment by fevxie** [comment]
Hi, guewen
     I got the mail and have already to push the code I have  migrated. there is a question about the  sale_automatic_workflow module and payment_method module ,  which directory this two module will be put in?

**Comment by yvaucher** [comment]
@fevxie `sale_automatic_workflow` can be found here:

https://github.com/OCA/e-commerce

**Comment by quamrul** [comment]
For odoo 8.0 there didn't have sale shop model again, user can set warehouse and pricelist directly on sale order. connector for odoo v7 we use the sale shop as a bridge between sale order and magento store. 
for odoo 8.0 what should do for this relationship. I'm pleasure to listen your opinions.

**Comment by quamrul** [comment]
Hi, guewen  
                   please give me the proper way how i import/ and export sales order from magneto to openerp v8(odoo)....in opeerp vs 7 its work fine but i have problem with v8 .my mail id is --asap quamrul.hoda@ymail.com

**Comment by guewen** [comment]
Hi @quamrul

If you have a bug while synchronising. please report a bug here.
If you have a general question about how to use the connector, please post
on the mailing list: https://launchpad.net/~openerp-connector-community

## 

Guewen Baconnier
Business Solutions Software Developer

Camptocamp SA
PSE A, CH-1015 Lausanne
Phone: +41 21 619 10 39
Office: +41 21 619 10 10
http://www.camptocamp.com/

**Comment by quamrul** [comment]
hi please show me the way , how i install odoo connector for odoo v8
yours quamrul hoda       On Thursday, 25 June 2015 1:47 PM, Guewen Baconnier notifications@github.com wrote:

 Hi @quamrul

If you have a bug while synchronising. please report a bug here.
If you have a general question about how to use the connector, please post
on the mailing list: https://launchpad.net/~openerp-connector-community

## 

Guewen Baconnier
Business Solutions Software Developer

Camptocamp SA
PSE A, CH-1015 Lausanne
Phone: +41 21 619 10 39
Office: +41 21 619 10 10
http://www.camptocamp.com/

**Comment by pedrobaeza** [comment]
You have the instructions in: http://odoo-connector.com/

Any further assistance, you will need to contact and hire a proper integrator service.
