### ISSUE TITLE
Tax included in price

### ISSUE THREAD

**Issue by dhecar** [OCA/connector-magento#84]
Hi, i'm triying to sync orders from magento to Openerp 7.

The price in Magento are tax included.

In the configuration for the connector I have checked (Prices include tax).

When the order is synced, openerp include againg the tax for the product.

Ex: In magento the price in catalog is 9.71 with a discount of 5% = 9.22€ this value with tax included.

Magento say:

Total   9,22 €
Shiping 10,00 €
taxes   1,60 €
Total = 19,22 €

Openerp say:

Product     IVA 21%                 9.22  
Shipping costs                 10.00
Subtotal                                  19.22 €
Tax                                         1.94 €
Total                                   21.16 €                    

It seems that apply the tax again to 9.22.

It's normal, or I'm doing something wrong??

**Comment by guewen** [comment]
Did you set the tax of the product to "tax included"?

**Comment by dhecar** [comment]
Yes i put tax included for the view in ERP configuration, but it doesn't work for me.

Finally I solved the problem:

In magento

Calc configurations:
Tax not included in catalog
Tax applied before discount
Apply discount with tax included

Front:
Show price with tax

In Openerp:

Views: prices not include price.

**Comment by l-arnold** [comment]
Seems issue can be closed.
