### ISSUE TITLE
Contributors Link misformed on connector-magento Module in Odoo

### ISSUE THREAD

**Issue by l-arnold** [OCA/connector-magento#99]
This is my Local current test IP.  Seems there should be some navigation between the IP and Authors

Off of my local (pre "install")   Module Information Page in Odoo.
## Built from OCA Gits last night.

(my IP number changed to "myip" to stop the link a bit)

Contributors links to:  https://myip/AUTHORS

gives:  Not Found

---

linked from: Local Modules / Magento Connector

https://myip/web#id=310&view_type=form&model=ir.module.module&menu_id=53&action=37

**Comment by pedrobaeza** [comment]
This is due to an outdated installation.

**Comment by l-arnold** [comment]
Just did a fresh pull yesterday from OCA Master.  Actually the link was on Github itself, not in my pull.  No big.
